### PR TITLE
Add hockeyapp distribution

### PR DESCRIPTION
**Pull request by yoonchulkoh**
I have implemented the minimum options.

HockeyApp API Document.
http://support.hockeyapp.net/kb/api/api-versions#upload-version

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
Wow, thank you very much!!  Saved me a lot of time.

**Comment by yoonchulkoh** [comment]
This is what's are pending?
Is there anything I should do?

**Comment by kishikawakatsumi** [comment]
Oh, I’m sorry. I was going to merge it but I forgot.

**Comment by kishikawakatsumi** [comment]
I'm going to release 0.0.8 including this PR, later.

**Comment by yoonchulkoh** [comment]
Thanks!

**Pull request merged**
